### PR TITLE
finished HW

### PR DESCRIPTION
**Pull request by sdkevorkian**
Comfort Level (1-5): 5

Completeness Level (1-5): 5

What did you think of this deliverable?: nice, simple, straightforward. using variables directly in strings is awesome

### CODE REVIEW

**Comment by connorjclark** [comment]
Which method of creating a sentence were you more comfortable with- the first part (with all the + signs) or the second part (the string interpolation- the backticks and dollar signs)? Why?

For the bonus question, what if...

1. the numbers array had zero elements?
2. the numbers array had elements, but they were all negative numbers?

**Comment by sdkevorkian** [comment]
I was way more comfortable with concatenating strings as that's what I'm more used to and my muscle memory goes to double quotes. BUT the string interpolation is awesome and more useful(I think) and I am determined to get that muscle memory down.

bonus ? additional code:


var numbers = [-2, -1];
var largestNum;

 if (numbers.length === 0){
    console.log("Please add numbers to your array");
  } else {
      largestNum = Number.NEGATIVE_INFINITY;       // just googled for this fun stuff
      for (i = 0; i < numbers.length; i++) {
      
        if (numbers[i] > largestNum) {
           largestNum = numbers[i];
        }
      }
}
console.log(largestNum);

**Comment by connorjclark** [comment]
Nice idea. There is however, a simpler solution.

You can set `largestNum` to be equal to the first element. `numbers[0]`. Then, start your loop at index 1 :)

**Comment by sdkevorkian** [comment]
yes, of course!!! i love it!!

**Pull request closed without merging**
